
import { Language } from './types';

export const TEXTS: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    customers: 'Customers',
    settings: 'Settings',
    cattle: 'Cattle Care', // New
    todaySummary: "Today's Summary",
    totalMilk: 'Total Milk',
    delivered: 'Delivered',
    pending: 'Pending',
    monthlyDue: 'Monthly Due',
    addCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',
    voiceAssistant: 'Voice Assistant',
    micListening: 'Listening...',
    micIdle: 'Tap to Speak',
    active: 'Active',
    inactive: 'Inactive',
    morning: 'Morning',
    evening: 'Evening',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    name: 'Name',
    nameHi: 'Name (Hindi)',
    phone: 'Phone',
    rate: 'Rate (₹/kg)',
    qty: 'Qty (kg)',
    address: 'Address',
    viewDetails: 'View Details',
    calendar: 'Calendar',
    timeline: 'Timeline', // Log
    addPayment: 'Add Payment',
    paymentHistory: 'Payment History',
    amount: 'Amount',
    mode: 'Mode',
    cash: 'Cash',
    online: 'Online',
    totalDue: 'Total Due',
    paid: 'Paid',
    balance: 'Balance',
    markDelivery: 'Mark Delivery',
    notDelivered: 'Not Delivered',
    confirmDelete: 'Are you sure you want to delete this customer? This cannot be undone.',
    language: 'Language',
    darkMode: 'Dark Mode',
    fontSize: 'Font Size',
    behavior: 'Behavior',
    very_good: 'Very Good',
    good: 'Good',
    ok: 'Ok',
    bad: 'Bad',
    reason: 'Reason',
    optional: 'Optional',
    updateEntry: 'Update Entry',
    selectSlot: 'Select Time',
    vacationMode: 'Vacation Mode',
    shareBill: 'Share Bill',
    billCopied: 'Bill copied to clipboard!',
    topConsumers: 'Top Consumers (This Month)',
    voiceHelp: 'Try "Add 2 liter for Ramesh" or "Delete Ramesh"',
    todaysRoute: "Today's Route",
    all: "All",
    quickMark: "Quick Mark",
    noPending: "All deliveries done for this route!",
    searchPlaceholder: "Search customer...",
    viewAll: "View All",
    recentDeliveries: "New Customers",
    markAll: "Mark All Delivered",
    markAllConfirm: "Mark all pending customers as delivered with default quantity?",
    // New Dashboard Texts
    thisMonth: "This Month",
    lastMonth: "Last Month",
    yearly: "Yearly",
    revenue: "Revenue",
    collected: "Collected",
    growth: "Growth",
    financialOverview: "Financial Overview",
    milkTrend: "Milk Supply Trend",
    collectionReport: "Collection Report",
    billedVsCollected: "Billed vs Collected",
    paymentModes: "Payment Modes",
    trend: "Trend",
    distribution: "Distribution",
    totalBill: "Total Bill",
    paymentStatus: "Payment Status",
    // Customer Status
    pastDue: "Past Due",
    currentBill: "Current Bill",
    advance: "Advance",
    settled: "Settled",
    // Active/Inactive Toggle
    stopMilk: "Stop Milk",
    startMilk: "Start Milk",
    stopMilkTitle: "Stop Delivery?",
    startMilkTitle: "Resume Delivery?",
    stopMilkMsg: "Milk delivery will be stopped. No daily entries will be made.",
    startMilkMsg: "Milk delivery started from today!",
    confirm: "Confirm",
    // Cattle Module
    addCattle: "Record Insemination",
    cowName: "Cow Name",
    cowColor: "Color / Identification",
    insemDate: "Insemination Date",
    expectedDate: "Expected Calving",
    daysPassed: "Days Passed",
    cattleList: "Cattle Records",
    noCattle: "No insemination records found.",
    confirmDeleteCattle: "Delete this record?",
    cowColorPlaceholder: "e.g. Black, White Patch...",
    noCustomersRoute: "No customers on this route",
    cowDetails: "Cattle Details",
    upcomingEvent: "Upcoming Delivery", // Changed
    daysLeft: "Days Left",
    overdue: "Overdue",
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    customers: 'ग्राहक',
    settings: 'सेटिंग्स',
    cattle: 'पशु पालन', // New
    todaySummary: 'आज का सारांश',
    totalMilk: 'कुल दूध',
    delivered: 'वितरित',
    pending: 'बाकी',
    monthlyDue: 'मासिक बकाया',
    addCustomer: 'ग्राहक जोड़ें',
    editCustomer: 'सुधार करें', // Changed from 'ग्राहक एडिट करें'
    voiceAssistant: 'वॉयस असिस्टेंट',
    micListening: 'सुन रहा हूँ...',
    micIdle: 'बोलने के लिए दबाएं',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    morning: 'सुबह',
    evening: 'शाम',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    name: 'नाम (English)',
    nameHi: 'नाम (हिंदी)',
    phone: 'फ़ोन',
    rate: 'रेट (₹/kg)',
    qty: 'मात्रा (kg)',
    address: 'पता',
    viewDetails: 'विवरण देखें',
    calendar: 'कैलेंडर',
    timeline: 'लॉग', // Changed from 'समय रेखा'
    addPayment: 'भुगतान जोड़ें',
    paymentHistory: 'भुगतान इतिहास',
    amount: 'राशि',
    mode: 'तरीका',
    cash: 'नकद',
    online: 'ऑनलाइन',
    totalDue: 'कुल बकाया',
    paid: 'प्राप्त किये', // Changed from 'जमा'
    balance: 'बकाया',
    markDelivery: 'दूध दर्ज करें',
    notDelivered: 'नहीं दिया',
    confirmDelete: 'क्या आप वाकई इस ग्राहक को हटाना चाहते हैं? इसे वापस नहीं लाया जा सकता।',
    language: 'भाषा',
    darkMode: 'डार्क मोड',
    fontSize: 'फ़ॉन्ट आकार',
    behavior: 'व्यवहार',
    very_good: 'बहुत अच्छा',
    good: 'अच्छा',
    ok: 'ठीक',
    bad: 'खराब',
    reason: 'कारण',
    optional: 'वैकल्पिक',
    updateEntry: 'सुधार करें', // Changed from 'एंट्री अपडेट करें'
    selectSlot: 'समय चुनें',
    vacationMode: 'छुट्टी मोड',
    shareBill: 'बिल शेयर करें',
    billCopied: 'बिल कॉपी कर लिया गया!',
    topConsumers: 'शीर्ष ग्राहक (इस माह)',
    voiceHelp: 'बोलें "Ramesh के लिए 2 लीटर जोड़ें" या "Ramesh को हटाएं"',
    todaysRoute: "आज का रूट",
    all: "सभी",
    quickMark: "मार्क करें",
    noPending: "इस रूट की सभी डिलीवरी हो गई!",
    searchPlaceholder: "ग्राहक खोजें...",
    viewAll: "सभी देखें",
    recentDeliveries: "नए ग्राहक",
    markAll: "सभी को मार्क करें",
    markAllConfirm: "क्या आप सभी बाकी ग्राहकों को 'वितरित' मार्क करना चाहते हैं?",
    // New Dashboard Texts
    thisMonth: "इस महीने",
    lastMonth: "पिछले महीने",
    yearly: "वार्षिक",
    revenue: "कुल कमाई",
    collected: "वसूली",
    growth: "वृद्धि",
    financialOverview: "वित्तीय सारांश",
    milkTrend: "दूध आपूर्ति रुझान",
    collectionReport: "वसूली रिपोर्ट",
    billedVsCollected: "बिल बनाम वसूली",
    paymentModes: "भुगतान के तरीके",
    trend: "रुझान",
    distribution: "वितरण",
    totalBill: "कुल बिल",
    paymentStatus: "भुगतान स्थिति",
    // Customer Status
    pastDue: "पिछला बकाया",
    currentBill: "हिसाब बाकी",
    advance: "एडवांस जमा",
    settled: "हिसाब चुकता",
    // Active/Inactive Toggle
    stopMilk: "दूध बंद करें",
    startMilk: "दूध चालू करें",
    stopMilkTitle: "दूध बंद करें?",
    startMilkTitle: "दूध चालू करें?",
    stopMilkMsg: "अब दूध नहीं जाएगा। ग्राहक को निष्क्रिय (Inactive) कर दिया जाएगा।",
    startMilkMsg: "अब दूध चालू हो गया है! आज से डिलीवरी शुरू।",
    confirm: "हाँ, करें",
    // Cattle Module
    addCattle: "गर्भाधान रिकॉर्ड करें",
    cowName: "गाय का नाम",
    cowColor: "रंग / पहचान",
    insemDate: "गर्भाधान की तारीख",
    expectedDate: "बच्चा देने की संभावित तारीख",
    daysPassed: "दिन बीत गए",
    cattleList: "पशु रिकॉर्ड",
    noCattle: "कोई रिकॉर्ड नहीं मिला।",
    confirmDeleteCattle: "क्या आप यह रिकॉर्ड हटाना चाहते हैं?",
    cowColorPlaceholder: "जैसे: काली, माथे पर सफ़ेद...",
    noCustomersRoute: "इस रूट पर कोई ग्राहक नहीं है",
    cowDetails: "पशु विवरण",
    upcomingEvent: "संभावित डिलीवरी", // Changed from 'आगामी कार्यक्रम' to positive term
    daysLeft: "दिन शेष",
    overdue: "तारीख निकल गई",
  }
};
